In [21]:
import cv2
import numpy as np
import os

In [13]:
img  = cv2.imread('data/1.jpg')
# resize image
resized_img = cv2.resize(img, (500, 300))
cv2.imshow("jelly fish", resized_img)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [20]:
# multiple image in same window
img  = cv2.imread('data/3.jpg')
print(img)

resized_img = cv2.resize(img, (500, 300))
h = np.hstack((resized_img, resized_img, resized_img))
v = np.vstack((h,h))
cv2.imshow("horizontal multiple image", v)
cv2.waitKey(5000)
cv2.destroyAllWindows()

[[[187 167 109]
  [189 167 109]
  [193 169 111]
  ...
  [192 157 107]
  [193 158 108]
  [192 158 105]]

 [[170 150  92]
  [171 149  91]
  [173 149  91]
  ...
  [174 139  89]
  [177 142  92]
  [178 144  91]]

 [[171 149  91]
  [170 146  88]
  [169 145  87]
  ...
  [174 139  89]
  [177 142  92]
  [178 144  91]]

 ...

 [[129 107 112]
  [125 103 115]
  [120  99 121]
  ...
  [158 175 184]
  [175 191 203]
  [168 184 197]]

 [[125 107 114]
  [122 103 118]
  [112  93 120]
  ...
  [176 191 200]
  [194 208 220]
  [192 205 221]]

 [[171 154 163]
  [173 155 172]
  [166 148 179]
  ...
  [206 218 230]
  [216 227 241]
  [210 223 239]]]


In [ ]:
list_name  = os.listdir("data")
list_name

['1.jpg', '2.jpg', '3.jpg']

In [32]:
for name in list_name:
    path = "data"
    img_name = path + "/" + name
    img = cv2.imread(img_name)
    if img is not None:
        img = cv2.resize(img, (500, 300))
        cv2.imshow("all images", img)
        cv2.waitKey(0)
    else:
        print(f"Failed to load image: {img_name}")
cv2.destroyAllWindows()
    